### ISSUE TITLE
Print Moves Function

### ISSUE THREAD

**Issue by SayLaVie** [SayLaVie/hex#2]
I talked to Dr Legrand on Friday, and he said it would be nice if the program output was like: at the end of every match, print out the board where each hex shows the owner of that tile and with which move that tile was taken. That way, we should be able to follow the progress of the match with only one output.

@mhoward104 , you might need to change the printBoard() function I have in hex.cpp to get that working correctly.

Why don't you work in the background branch -- you can modify the hex.cpp if you need to change the printBoard() function [be careful about changing other functions], and you can add a file to work on the printMoves() function [that way @Carvedlaser can still work on the hexMain.cpp without having to worry about merge conflicts].

Do you have different ideas or does that sound good?

**Comment by mhoward104** [comment]
Sounds good!

**Comment by mhoward104** [comment]
Something like this:  
      -  B1  -
   A2 A1 -
B2 - A3

or this:

      -  B  -
   A  A -
B - A
PlayerA: (2,2), (0,2), (3,0)
PlayerB: (2,3), (0,0)

**Comment by SayLaVie** [comment]
Like the first one

**Comment by mhoward104** [comment]
Updated to the PrintBoard() to print the move and turn it was played
