### ISSUE TITLE
Agent Structure

### ISSUE THREAD

**Issue by Carvedlaser** [SayLaVie/hex#3]
Okay I've edited the batch file and I believe it will work. The agents have to be constructed in a manner similar to what we did for the agent challenges.

All agents must:

-  be of return type int
-  be named in the same manner as before, in this case "hexAgentSmith.cpp"
-  have the function named in the same manner "hexAgentSmith.cpp"

The only other stipulation for the project as a whole is that the files must be named hexMain.cpp
hex.h, and hex.cpp

All of this seems to be pretty easy and shouldn't be a problem

I'm uploading the batch file here in case anyone wants to double check me or use it
[hexBuild.zip](https://github.com/SayLaVie/hex/files/949928/hexBuild.zip)

**Comment by SayLaVie** [comment]
Looks good, I added the file to the master branch.  I changed funcSignature slightly to reflect the function structure Jacob used in his agentStraight, which also has a parameter whichPlayer.
